"""Blender-side scene-generation script builder for FrameLabs.

Feature 10's "Run Blender Script" / "Import Sequence" / "Configure Camera"
/ "Set Timeline" / "Save Blend" steps. This module builds the *text* of a
Python script that Blender itself will run (via `--python`, see
launcher.py) -- it never imports `bpy` and never runs inside Blender's own
process. Per the Developer Handbook, Blender integration is isolated to
this package; this module in particular is pure string-generation, so it
stays fully unit-testable with no real Blender install anywhere in the
test environment.

The generated script embeds the BlenderManifest's data directly as
literals (via json.dumps, which produces valid Python literal syntax for
every value BlenderManifest can hold) rather than having the Blender-side
script re-read the manifest JSON file at runtime -- this keeps the
generated script fully self-contained and correct even if the manifest
file is later moved, cleaned up, or overwritten by a subsequent export.
"""

from __future__ import annotations

import json
from pathlib import Path

from framelabs.blender.exporter import BlenderExportError, BlenderManifest

SCENE_SCRIPT_FILENAME = "generate_scene.py"


def generate_scene_script(manifest: BlenderManifest) -> str:
    """Build the full text of the Blender-side scene-generation script.

    Args:
        manifest: The manifest describing the project to build a scene
            from -- see exporter.build_manifest().

    Returns:
        A complete, self-contained Python script (valid to run via
        `blender --python <path>`) that:
            - clears the default startup scene
            - sets fps, resolution, and the frame range
            - creates a camera with the manifest's focal length
            - loads the frame sequence as a camera background image at
              50% opacity, visible through the camera view
            - imports every frame as a Video Sequence Editor image
              sequence, in Timeline order
            - enables the compositor (use_nodes)
            - saves the result to manifest.blend_output_path
    """
    frame_paths_literal = json.dumps(manifest.frame_paths)
    fps_literal = json.dumps(manifest.fps)
    resolution_literal = json.dumps(list(manifest.resolution))
    focal_length_literal = json.dumps(manifest.focal_length_mm)
    blend_output_literal = json.dumps(manifest.blend_output_path)

    lines = [
        '"""Auto-generated by FrameLabs -- do not edit by hand.',
        "",
        'Regenerated fresh every time "Open in Blender" runs; any manual',
        'edits here will be silently overwritten next time.\n"""',
        "",
        "import os",
        "",
        "import bpy",
        "",
        f"FRAME_PATHS = {frame_paths_literal}",
        f"FPS = {fps_literal}",
        f"RESOLUTION = {resolution_literal}",
        f"FOCAL_LENGTH_MM = {focal_length_literal}",
        f"BLEND_OUTPUT_PATH = {blend_output_literal}",
        "",
        "",
        "def build_scene():",
        "    scene = bpy.context.scene",
        "",
        "    # Clear the default startup scene (cube, light, camera) --",
        "    # every FrameLabs-generated scene starts from a blank slate.",
        '    bpy.ops.object.select_all(action="SELECT")',
        "    bpy.ops.object.delete(use_global=False)",
        "",
        "    # --- Timeline / FPS / Resolution ---",
        "    scene.render.fps = FPS",
        "    scene.render.resolution_x = RESOLUTION[0]",
        "    scene.render.resolution_y = RESOLUTION[1]",
        "    scene.frame_start = 1",
        "    scene.frame_end = max(1, len(FRAME_PATHS))",
        "",
        "    # --- Camera ---",
        "    bpy.ops.object.camera_add(",
        "        location=(0, -5, 0), rotation=(1.5708, 0, 0)",
        "    )",
        "    camera_obj = bpy.context.object",
        '    camera_obj.name = "FrameLabs Camera"',
        "    camera_obj.data.lens = FOCAL_LENGTH_MM",
        "    scene.camera = camera_obj",
        "",
        "    # --- Camera background image ---",
        "    # Loads the same frame sequence as a camera background image at",
        "    # 50% opacity, visible through the camera view while animating --",
        "    # this is separate from the VSE strip below (Blender's Background",
        "    # Images system, not the sequencer), and is what makes the",
        "    # captured reference footage actually show up behind whatever is",
        "    # built in the scene.",
        "    if FRAME_PATHS:",
        "        bg_image = bpy.data.images.load(FRAME_PATHS[0])",
        '        bg_image.source = "SEQUENCE"',
        "        camera_obj.data.show_background_images = True",
        "        background = camera_obj.data.background_images.new()",
        "        background.image = bg_image",
        "        background.alpha = 0.5",
        "        background.image_user.frame_start = 1",
        "        background.image_user.frame_duration = len(FRAME_PATHS)",
        "        background.image_user.use_auto_refresh = True",
        "",
        "    # --- Image sequence (Video Sequence Editor) ---",
        "    # Timeline order is guaranteed by exporter.py's",
        "    # _ordered_frame_paths() -- this script trusts FRAME_PATHS'",
        "    # order as-is rather than re-sorting.",
        "    if FRAME_PATHS:",
        "        if scene.sequence_editor is None:",
        "            scene.sequence_editor_create()",
        "        strip = scene.sequence_editor.sequences.new_image(",
        '            name="FrameLabs Sequence",',
        "            filepath=FRAME_PATHS[0],",
        "            channel=1,",
        "            frame_start=1,",
        "        )",
        "        for frame_path in FRAME_PATHS[1:]:",
        "            strip.elements.append(os.path.basename(frame_path))",
        "",
        "    # --- Compositor ---",
        "    # Enabling use_nodes creates Blender's default Render Layers",
        "    # -> Composite node pair automatically -- no manual node",
        "    # construction needed for a v1 scene.",
        "    scene.use_nodes = True",
        "",
        "    # --- Save ---",
        "    bpy.ops.wm.save_as_mainfile(filepath=BLEND_OUTPUT_PATH)",
        "",
        "",
        "build_scene()",
        "",
    ]
    return "\n".join(lines)


def write_scene_script(manifest: BlenderManifest, output_dir: Path) -> Path:
    """Write the generated scene script to `output_dir`.

    Args:
        manifest: See generate_scene_script().
        output_dir: Directory the script should be written into --
            callers pass `project_path / "cache" / "blender"`, the same
            directory exporter.write_manifest() uses, so both the
            manifest JSON and its generator script live side by side.

    Returns:
        Path to the written script file.

    Raises:
        BlenderExportError: If the directory can't be created or the
            file can't be written.
    """
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
        script_path = output_dir / SCENE_SCRIPT_FILENAME
        script_path.write_text(generate_scene_script(manifest))
    except OSError as exc:
        raise BlenderExportError(
            f"Failed to write Blender scene script: {exc}"
        ) from exc

    return script_path
